### ISSUE TITLE
本人使用vs2012编译，出现warning并无法编译通过，现已找到解决办法分享一下。

### ISSUE THREAD

**Issue by orcasdli** [guoming0000/KinectV2#1]
warning内容：该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失。
然后提示kinect 类建立有问题云云。后来发现是编码问题，我估计建立者应该是从网页copy进来的程序，有些不友好的字符集（不懂术语，见谅了）。
方法如下：https://blog.csdn.net/lcb_coconut/article/details/76136725
另存为另一种编码覆盖掉就好。
需要win32编译。

**Comment by guoming0000** [comment]
1. warning不会导致编译不过
2. 这个和kinect没啥关系
